# MODELOS PARA INTELIGENCIA ARTIFICIAL-codigo avanzado

In [1]:
import pandas as pd


train = pd.read_csv('D:/python/iris/train.csv')
test = pd.read_csv('D:/python/iris/test.csv')

In [2]:
train.head()

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0   1           6.0          2.2           5.0          1.5   virginica
1   2           6.1          2.8           4.7          1.2  versicolor
2   3           5.0          3.5           1.3          0.3      setosa
3   4           6.1          2.6           5.6          1.4   virginica
4   5           5.0          3.2           1.2          0.2      setosa

In [3]:
test.head()

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0  106           4.4          3.2           1.3          0.2      setosa
1  107           5.2          3.5           1.5          0.2      setosa
2  108           5.7          2.5           5.0          2.0   virginica
3  109           6.6          2.9           4.6          1.3  versicolor
4  110           5.5          4.2           1.4          0.2      setosa

In [4]:
train_test_data = [train, test] 

species_mapping = {"setosa": 0, "versicolor": 1, "virginica": 2}
for dataset in train_test_data:
    dataset['Species'] = dataset['Species'].map(species_mapping)

In [5]:
train.head()

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0   1           6.0          2.2           5.0          1.5        2
1   2           6.1          2.8           4.7          1.2        1
2   3           5.0          3.5           1.3          0.3        0
3   4           6.1          2.6           5.6          1.4        2
4   5           5.0          3.2           1.2          0.2        0

In [6]:
test.head()

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0  106           4.4          3.2           1.3          0.2        0
1  107           5.2          3.5           1.5          0.2        0
2  108           5.7          2.5           5.0          2.0        2
3  109           6.6          2.9           4.6          1.3        1
4  110           5.5          4.2           1.4          0.2        0

In [7]:
test_data = test.drop('Species', axis=1)
target_test = test['Species']

test_data.shape, target_test.shape

((45, 5), (45,))

In [8]:
train_data = train.drop('Species', axis=1)
target = train['Species']

train_data.shape, target.shape

((105, 5), (105,))

In [9]:
train_data.head(10)

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0   1           6.0          2.2           5.0          1.5
1   2           6.1          2.8           4.7          1.2
2   3           5.0          3.5           1.3          0.3
3   4           6.1          2.6           5.6          1.4
4   5           5.0          3.2           1.2          0.2
5   6           5.4          3.4           1.5          0.4
6   7           5.0          3.3           1.4          0.2
7   8           6.3          3.4           5.6          2.4
8   9           7.2          3.2           6.0          1.8
9  10           4.6          3.4           1.4          0.3

In [10]:
test_data.head(10)

ID  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0  106           4.4          3.2           1.3          0.2
1  107           5.2          3.5           1.5          0.2
2  108           5.7          2.5           5.0          2.0
3  109           6.6          2.9           4.6          1.3
4  110           5.5          4.2           1.4          0.2
5  111           7.7          3.0           6.1          2.3
6  112           6.7          3.0           5.2          2.3
7  113           4.7          3.2           1.6          0.2
8  114           4.9          3.1           1.5          0.2
9  115           4.7          3.2           1.3          0.2

# MODELAMIENTO


In [11]:
# Importing Classifier Modules
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn import datasets
from sklearn import tree
from sklearn import metrics

import numpy as np

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 6 columns):
ID              105 non-null int64
Sepal.Length    105 non-null float64
Sepal.Width     105 non-null float64
Petal.Length    105 non-null float64
Petal.Width     105 non-null float64
Species         105 non-null int64
dtypes: float64(4), int64(2)
memory usage: 5.0 KB


# Por Validacion Cruzada se compara:

In [13]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)

# KNN

In [14]:
clf = KNeighborsClassifier(n_neighbors = 5,p=2, metric='minkowski')
clf.fit(train_data, target)

# generate evaluation metrics in train
print (metrics.accuracy_score(target, clf.predict(train_data)))
print (metrics.confusion_matrix(target, clf.predict(train_data)))
print (metrics.classification_report(target, clf.predict(train_data)))




0.780952380952381
[[25  5  0]
 [ 4 30  4]
 [ 1  9 27]]
             precision    recall  f1-score   support

          0       0.83      0.83      0.83        30
          1       0.68      0.79      0.73        38
          2       0.87      0.73      0.79        37

avg / total       0.79      0.78      0.78       105



In [15]:
clf = KNeighborsClassifier(n_neighbors = 5,p=2, metric='minkowski')
clf.fit(test_data, target_test)

# generate evaluation metrics in test
print (metrics.accuracy_score(target_test, clf.predict(test_data)))
print (metrics.confusion_matrix(target_test, clf.predict(test_data)))
print (metrics.classification_report(target_test, clf.predict(test_data)))


0.7777777777777778
[[19  1  0]
 [ 4  5  3]
 [ 1  1 11]]
             precision    recall  f1-score   support

          0       0.79      0.95      0.86        20
          1       0.71      0.42      0.53        12
          2       0.79      0.85      0.81        13

avg / total       0.77      0.78      0.76        45



In [16]:
scoring = 'accuracy'
score = cross_val_score(clf, train_data, target, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[0.45454545 0.54545455 0.45454545 0.45454545 0.27272727 0.5
 0.3        0.2        0.5        0.6       ]


In [17]:
# Score
round(np.mean(score)*100, 2)

42.82

# ARBOLES DE DECISION

In [18]:
clf = DecisionTreeClassifier()
scoring = 'accuracy'
score = cross_val_score(clf, train_data, target, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[1.         1.         0.90909091 0.81818182 0.90909091 0.9
 0.9        1.         0.9        1.        ]


In [19]:
#Score
round(np.mean(score)*100, 2)

93.36

# RANDOM FOREST

In [20]:
clf = RandomForestClassifier(n_estimators=13)
scoring = 'accuracy'
score = cross_val_score(clf, train_data, target, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[1.         1.         1.         0.90909091 0.90909091 0.9
 0.8        1.         0.9        1.        ]


In [21]:
# Score
round(np.mean(score)*100, 2)

94.18

# NAIVE BAYES

In [22]:
clf = GaussianNB()
scoring = 'accuracy'
score = cross_val_score(clf, train_data, target, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[1.         1.         1.         0.90909091 0.90909091 1.
 1.         0.9        0.9        1.        ]


In [23]:
# Score
round(np.mean(score)*100, 2)

96.18

# MAQUINA DE VECTORES

In [24]:
clf = SVC(kernel='linear', C=1.0, random_state=0)
clf.fit(train_data, target)

# generate evaluation metrics in train
print (metrics.accuracy_score(target, clf.predict(train_data)))
print (metrics.confusion_matrix(target, clf.predict(train_data)))
print (metrics.classification_report(target, clf.predict(train_data)))



0.9714285714285714
[[30  0  0]
 [ 0 36  2]
 [ 0  1 36]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        30
          1       0.97      0.95      0.96        38
          2       0.95      0.97      0.96        37

avg / total       0.97      0.97      0.97       105



In [25]:
clf = SVC(kernel='linear', C=1.0, random_state=0)
clf.fit(test_data, target_test)

# generate evaluation metrics in test
print (metrics.accuracy_score(target_test, clf.predict(test_data)))
print (metrics.confusion_matrix(target_test, clf.predict(test_data)))
print (metrics.classification_report(target_test, clf.predict(test_data)))

0.9555555555555556
[[20  0  0]
 [ 0 11  1]
 [ 0  1 12]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        20
          1       0.92      0.92      0.92        12
          2       0.92      0.92      0.92        13

avg / total       0.96      0.96      0.96        45



In [26]:
scoring = 'accuracy'
score = cross_val_score(clf, train_data, target, cv=k_fold, n_jobs=1, scoring=scoring)
print(score)

[1.         1.         1.         0.90909091 1.         0.9
 1.         1.         0.9        1.        ]


In [27]:
round(np.mean(score)*100,2)

97.09

# Testing

In [31]:
clf = SVC()
clf.fit(train_data, target)

test_data = test.drop("ID", axis=1).copy()
prediction = clf.predict(test_data)

In [32]:
submission = pd.DataFrame({
        "ID": test["ID"],
        "Species": prediction
    })

submission.to_csv('submission.csv', index=False)

In [33]:
submission = pd.read_csv('submission.csv')
submission.head()

ID  Species
0  106        0
1  107        0
2  108        2
3  109        0
4  110        0